spring:
  application:
    name: auth-platform

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authplatform}
    username: ${DB_USER:authplatform}
    password: ${DB_PASSWORD:authplatform}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10s

  security:
    filter:
      order: 5

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    io.authplatform: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application-specific configuration
auth-platform:
  security:
    api-keys:
      enabled: true
      header-name: X-API-Key
      # Development keys (DO NOT use in production)
      # In production, use environment variables or secrets management
      keys:
        dev-key-org1-abc123: org-1
        dev-key-org2-def456: org-2
        test-key-xyz789: test-org
  opa:
    url: ${OPA_URL:http://localhost:8181}
    timeout-ms: 100
  cache:
    l1:
      ttl-seconds: 10
      max-entries: 10000
    l2:
      ttl-seconds: 300
      max-entries: 1000000
  rate-limit:
    default:
      capacity: 1000
      refill-rate: 1000
      refill-period-minutes: 1
